In [24]:

import pandas as pd
df = pd.read_csv(r'Bookings_ola.csv')

In [25]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN

In [26]:
df.describe(include='all')

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
count,103024,103024,103024,103024,103024,103024,103024,103024,63967.000000,63967.000000,...,18434,63967,3926,103024.000000,63967,103024.000000,63967.000000,63967.000000,103024,0.0
unique,40214,1440,103024,4,94544,7,50,50,NaN,NaN,...,4,2,3,NaN,4,NaN,NaN,NaN,1,NaN
top,2024-07-13 18:53:00,00:53:00,CNR7153255142,Success,CID954071,Prime Sedan,Banashankari,Peenya,NaN,NaN,...,Personal & Car related issue,No,Customer Demand,NaN,Cash,NaN,NaN,NaN,#NAME?,NaN
freq,10,101,1,63967,5,14877,2201,2159,NaN,NaN,...,6542,60041,1601,NaN,35022,NaN,NaN,NaN,103024,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.876952,84.873372,...,NaN,NaN,NaN,548.751883,NaN,14.189927,3.997457,3.998313,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.803640,36.005100,...,NaN,NaN,NaN,536.541221,NaN,15.776270,0.576834,0.578957,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,25.000000,...,NaN,NaN,NaN,100.000000,NaN,0.000000,3.000000,3.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,55.000000,...,NaN,NaN,NaN,242.000000,NaN,0.000000,3.500000,3.500000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.000000,85.000000,...,NaN,NaN,NaN,386.000000,NaN,8.000000,4.000000,4.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.000000,115.000000,...,NaN,NaN,NaN,621.000000,NaN,26.000000,4.500000,4.500000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.000000,145.000000,...,NaN,NaN,NaN,2999.000000,NaN,49.000000,5.000000,5.000000,NaN,NaN

In [27]:
df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          39057
C_TAT                          39057
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                 39057
Customer_Rating                39057
Vehicle Images                     0
Unnamed: 20                   103024
dtype: int64

In [28]:
df['Driver_Ratings'] = df.groupby('Vehicle_Type')['Driver_Ratings'].transform(lambda x:x.fillna(x.median()))

In [29]:
df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          39057
C_TAT                          39057
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                     0
Customer_Rating                39057
Vehicle Images                     0
Unnamed: 20                   103024
dtype: int64

In [30]:
df['Customer_Rating'] = df.groupby('Vehicle_Type')['Customer_Rating'].transform(lambda x:x.fillna(x.median()))

In [31]:
df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          39057
C_TAT                          39057
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                     0
Customer_Rating                    0
Vehicle Images                     0
Unnamed: 20                   103024
dtype: int64

In [32]:
df['V_TAT'] = df.groupby('Vehicle_Type')['V_TAT'].transform(lambda x: x.fillna(x.median()))

df['C_TAT'] = df.groupby('Vehicle_Type')['C_TAT'].transform(lambda x: x.fillna(x.median()))

In [33]:
df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                              0
C_TAT                              0
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                     0
Customer_Rating                    0
Vehicle Images                     0
Unnamed: 20                   103024
dtype: int64

In [34]:
df.columns = df.columns.str.lower()

In [35]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'v_tat', 'c_tat',
       'canceled_rides_by_customer', 'canceled_rides_by_driver',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'payment_method', 'ride_distance', 'driver_ratings', 'customer_rating',
       'vehicle images', 'unnamed: 20'],
      dtype='object')

In [36]:
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,v_tat,c_tat,...,canceled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,payment_method,ride_distance,driver_ratings,customer_rating,vehicle images,unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,...,Personal & Car related issue,NaN,NaN,444,NaN,0,4.0,4.0,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,...,NaN,NaN,NaN,384,NaN,0,4.0,4.0,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN

In [37]:
df = df.drop('vehicle images', axis=1)

In [38]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'v_tat', 'c_tat',
       'canceled_rides_by_customer', 'canceled_rides_by_driver',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'payment_method', 'ride_distance', 'driver_ratings', 'customer_rating',
       'unnamed: 20'],
      dtype='object')

In [39]:
df.drop('unnamed: 20', axis=1, inplace=True)

In [40]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'v_tat', 'c_tat',
       'canceled_rides_by_customer', 'canceled_rides_by_driver',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'payment_method', 'ride_distance', 'driver_ratings', 'customer_rating'],
      dtype='object')

In [41]:
df.loc[df['booking_status'] != 'Success', 'payment_method'] = 'No Payment'

In [42]:
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,v_tat,c_tat,canceled_rides_by_customer,canceled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,payment_method,ride_distance,driver_ratings,customer_rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,NaN,Personal & Car related issue,NaN,NaN,444,No Payment,0,4.0,4.0
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,NaN,NaN,NaN,384,No Payment,0,4.0,4.0
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0

In [43]:
df.isnull().sum()

date                              0
time                              0
booking_id                        0
booking_status                    0
customer_id                       0
vehicle_type                      0
pickup_location                   0
drop_location                     0
v_tat                             0
c_tat                             0
canceled_rides_by_customer    92525
canceled_rides_by_driver      84590
incomplete_rides              39057
incomplete_rides_reason       99098
booking_value                     0
payment_method                    0
ride_distance                     0
driver_ratings                    0
customer_rating                   0
dtype: int64

In [44]:
pip install psycopg2-binary sqlalchemya

Requirement already satisfied: psycopg2-binary in c:\users\anshc\anaconda3\lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlalchemya (from versions: none)
ERROR: No matching distribution found for sqlalchemya

In [46]:
from sqlalchemy import create_engine
import pandas as pd

password = "Ansh1234"
username = "postgres"
host = "localhost"
port = "5432"
database = "OLA"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
table_name = "ola"

df.to_sql(table_name, engine, if_exists='replace', index=False)
print(f"DataFrame loaded into PostgreSQL table: {table_name} in database {database}")

DataFrame loaded into PostgreSQL table: ola in database OLA